# Enable C++ support
language: cpp
sudo: required
install:
    - sudo apt-get install software-properties-common
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - sudo apt-get -y update
    - sudo apt-get -y install cmake
    - sudo apt-get -y upgrade cmake 


# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cd src_c
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARE_TYPE=SHARED && make -j2 && make aitest
