# Enable C++ support
language: cpp
dist: xenial
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cd src_c
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARE_TYPE=SHARED && make -j2 && make aitest
